# development:
#   adapter: postgresql
#   encoding: unicode
#   database: crowd_sourced_city_api
#   pool: 5
#   username: sclspatial
#   host: sclspatial-02.cccgllkjaf7f.us-east-1.rds.amazonaws.com
#   timeout: 5000
#   password: senseable10400
#   schema_search_path: public

development:
  adapter: postgresql
  encoding: unicode
  database: crowd_sourced_city_api_0510
  pool: 5
  username: sclspatial
  host: sclspatial-02.cccgllkjaf7f.us-east-1.rds.amazonaws.com
  timeout: 5000
  password: senseable10400
  schema_search_path: public
  # adapter: postgresql
  # encoding: unicode
  # database: crowd_sourced_city_api_development
  # pool: 5
  # username: wonyoungso
  # host: localhost
  # timeout: 5000
  # password: 
  # schema_search_path: public

test:
  adapter: postgresql
  encoding: unicode
  database: crowd_sourced_city_api_test
  pool: 5
  username: wonyoungso
  host: localhost
  timeout: 5000
  password: 
  schema_search_path: public

production:
  adapter: postgresql
  encoding: unicode
  database: crowd_sourced_city_api_0510
  pool: 5
  username: sclspatial
  host: sclspatial-02.cccgllkjaf7f.us-east-1.rds.amazonaws.com
  timeout: 5000
  password: senseable10400
  schema_search_path: public